
export const CREATE_TIMEBLOCK = "CREATE_TIMEBLOCK";
export const CREATE_DAY = "CREATE_DAY";

export const ADD_NOTES_TO_TIMEBLOCK = "ADD_NOTES_TO_TIMEBLOCK";

export const EDIT_TIMEBLOCK = "EDIT_TIMEBLOCK";

export const DELETE_TIMEBLOCK = "DELETE_TIMEBLOCK";

export const ADD_JOURNAL_TO_DAY = "ADD_JOURNAL_TO_DAY";